<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RSI1505" ignored="0" name="br.com.rsinet.hub_TDD" tests="6" failures="1" timestamp="2020-01-27T10:26:58 BRT" time="111.116" errors="0">
  <testcase name="testaBuscaLupaInvalido" time="3.939" classname="br.com.rsinet.hub_TDD.testes.TestBuscaLupa"/>
  <testcase name="testaBuscaLupaValido" time="3.208" classname="br.com.rsinet.hub_TDD.testes.TestBuscaLupa"/>
  <testcase name="testaBuscaCliqueInvalido" time="5.135" classname="br.com.rsinet.hub_TDD.testes.TesteBuscaClique"/>
  <testcase name="testaBuscaCliqueValido" time="5.981" classname="br.com.rsinet.hub_TDD.testes.TesteBuscaClique"/>
  <testcase name="testeCadastroValido" time="7.562" classname="br.com.rsinet.hub_TDD.testes.TesteCadastro"/>
  <testcase name="testeCadastroInvalido" time="20.738" classname="br.com.rsinet.hub_TDD.testes.TesteCadastro">
    <failure type="java.lang.AssertionError" message="did not expect to find [false] but found [true]">
      <![CDATA[java.lang.AssertionError: did not expect to find [false] but found [true]
at br.com.rsinet.hub_TDD.testes.TesteCadastro.testeCadastroInvalido(TesteCadastro.java:132)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testeCadastroInvalido -->
</testsuite> <!-- br.com.rsinet.hub_TDD -->
